### ISSUE TITLE
Asynchronous Tick Loop

### ISSUE THREAD

**Issue by Hexcede** [screeps/screeps#115]
**What** Something that I think would be greatly appreciated would be an asynchronous version of the tick loop function.

**How** Instead of the loop function being synchronous we could define it as `async loop()`. We could have events, promises, etc and we can simply use `await Promise.all(promises)` at the end of our code to allow for efficient multitasking in our code.

**Why** I think that this would greatly improve the performance capabilities of some scripts if implemented properly and would reduce server strain.

**Comment by PostCrafter** [comment]
I've thought about this as well before, but since all of the screeps API and exposed JavaScript API is synchronous (there's no `fetch` or similar) I don't see any benefit of actually using async in code. There's nothing you can actually run asynchronous in a useful manner, even if it were possible.
What is possible is using generator functions to yield your functions and only continue execution based on some conditions (like CPU).

**Comment by michalusio** [comment]
@Hexcede Using a rollup plugin like `rollup-plugin-async` (I had to make a few changes to it because it's a bit outdated) you can automatically transpile async/await into generator functions using a Promise class.
Then you can supplant your own Promise implementation, and at the end of your loop method just do something like `runPromises()` which resolves the queued promises in a loop.

You can then use async/await just like you would in Node code.
As @RiftLurker said, the game API is synchronous and there's no point in making it asynchronous as the game is running in ticks. however you can make wrappers around it and have them return Promises which resolve the next tick or something.

**Comment by o4kapuk** [comment]
As said above, using async in code can not provide any benefit due to synchronous  game API, and, more importantly, because server runs game scripts on a single dedicated core.

**Comment by Hexcede** [comment]
> As said above, using async in code can not provide any benefit due to synchronous game API, and, more importantly, **because server runs game scripts on a single dedicated core**.

This certainly is disappointing for what I was hoping for. I unfortunately didn't really respond to any of the comments above, but, I honestly never really even considered the game APIs. I've always known they're (mostly:tm:) processed after the loop, so I think of them more as array push calls or something, it's only changing some state for later.

The main interest to me wasn't really interacting with the game at all, or doing work across ticks, it was around doing stuff during the tick, and designing the code in a more optimal way as a result of promises, since it allows structure to be broken down a lot more. It might still be that the promises are processed fully synchronously on one thread, but they (similar to generator functions) create a sort of illusion that they aren't and that is beneficial in some ways. It's unfortunately impossible to use them reliably without some sort of support inside the game loop, since the promises aren't processed until it's too late to do anything with them.

@michalusio's suggestion of using `rollup-plugin-async` sounds *promising* (pun totally intended). Babel also has an interesting transform called `regenerator` which I saw the Arena client using but that's for turning generator functions into switch statements. I'm sure I could totally use this to save generator states onto Memory.

Truthfully, I've never fully understood how the performance benefit of promises is meant to come into play, so I've mostly trusted the idea that Promise = better without much thought and have seen good results from it, so I can't really fairly say a lot on the performance side of things.

---

Ultimately I think my issue couldn't been formatted/phrased better to emphasize that the real benefit I actually want is the control flow aspect, I don't think it makes sense for me to have submitted it the way that I did. Thanks for looking at this :smile:

**Comment by Pauan** [comment]
> @Hexcede Truthfully, I've never fully understood how the performance benefit of promises is meant to come into play

The performance benefits of Promises is that they allow you to handle thousands of I/O connections efficiently. For example, a web server might have millions of sockets running at the same time. Or you might be reading from thousands of files simultaneously. Promises can handle that very well, because the I/O operations are happening in the background.

But if you're not doing I/O things... if it's just synchronously updating some game state, then Promises will make your code *slower*, because Promises are slower than synchronous functions.

**Comment by michalusio** [comment]
@Hexcede @Pauan @o4kapuk 

The point of Promises as I have described them (transpiling promises into generators) is about using async/await notation for an OS-style bot. That way you don't have to mess around with generators and scheduling - the Promise loop does that for you, you don't need to see it.

That said, adding native support in Screeps is not necessary at all in this case, i.e. the control flow aspect is obtained by transpiling Promises to generators.
