### ISSUE TITLE
Critical XSS/RCE Vulnerability in Screeps Client with Nwjs Environment

### ISSUE THREAD

**Issue by MingZeY** [screeps/screeps#162]
**Description:**
When entering the following code into the Screeps game client(or write it in a JavaScript file):
```js
console.log(`<script>nw.require('child_process').exec('start cmd /k echo A SERIOUS XSS Bug in Screeps Client with Nwjs environment')</script>`)

```
An XSS (Cross-Site Scripting) vulnerability is triggered which can potentially allow the execution of arbitrary code on the client-side.

**Impact:**
This issue poses a significant security threat as it allows an attacker to execute any code on a client's machine.

**Steps to Reproduce:**
1. Open the Screeps game client.
2. Input the above code in console.
3. Observe that the XSS attack is triggered, and the arbitrary code is executed.

**Expected Behavior:**
The client should safely handle and sanitize all inputs, ensuring that no malicious scripts or code can be executed.

**Comment by MingZeY** [comment]
This means that even if the code is executed on the official server, unknown source code may still attack careless players. If the attacker provides the code to other players and the player applies it to their own game without reviewing it, it is highly likely to silently trigger the attack

**Comment by KingSupernova31** [comment]
You're underselling the severity of this. The stated threat vector of "idiot blindly executes code that someone else gives them" is impossible to completely fix without taking their computer away from them, people can always make poor decisions. The bigger problem here is that this XSS can be triggered without any help from the victim; if their code includes any console.log statement that references any game object someone else has any control over, such as logging the name of someone else's creep, that's all an attacker needs to gain access.

**Comment by MingZeY** [comment]
Your concern is correct. I have checked the relevant source code and although the official has filtered enough places, players may still be attacked by carefully constructed environments. In fact, I have found a feasible Poc chain in the widely used Overmind.

**Comment by TylerSeanRau** [comment]
@o4kapuk, @artch, @AlinaNova21, @szymex73 any thoughts here? would be great to have this addressed

**Comment by o4kapuk** [comment]
We do not see this as a serious security threat.

@MingZeY As the console output is only available to the player executing the code, sanitizing here is essentially protecting the player from their own code, which does not seem necessary. Also, some players use it for client customization, like those in the [screepers/screeps-snippets](https://github.com/screepers/screeps-snippets) repo, which we do not want to prohibit.

@KingSupernova31 By design, all players have their own copies of game objects created in their isolates.

If anyone has a working PoC of an attack that allows an attacker to inject unescaped HTML/script code into another player's console, please send the details and reproducing code to contact@screeps.com. Publishing such things may be risky, so we recommend sharing this information privately. We will review it to determine the severity.
