### ISSUE TITLE
Log to stdout/stderr

### ISSUE THREAD

**Issue by jkroepke** [screeps/screeps#24]
Hi!

It's possible to send the logs to stdout? It would be easier for docker or systemd environments to send the logs to stdout instead write logs into files.

**Comment by ags131** [comment]
Note that when launching without the launcher it does log to stdout, my docker image (ags131/screeps-server on Dockerhub) logs to stdout when launching individual modules

**Comment by jkroepke** [comment]
But I won't build a own launcher or manage self the bootstrap process for this game.

**Comment by artch** [comment]
You should not use the standard launcher when launch via systemd or docker. All processes should be launched individually instead. It's a more natural approach in this case, and all output will go to stdout/stderr then. 

In order to accomplish it, you don't need to write your own launcher. Simply check [this file](https://github.com/screeps/launcher/blob/master/lib/start.js) and launch all processes in the same way with their corresponding environment variables.
