### ISSUE TITLE
Cannot start on Ubuntu server properly

### ISSUE THREAD

**Issue by EvanAbra** [screeps/screeps#72]
This is the screenshot when I excute the command " sudo screeps start". It outputs this kind of things over and over again and doesn't seem to have an end.
![image](https://user-images.githubusercontent.com/27116366/34349906-f27046fc-ea4e-11e7-8b7d-81b3d8aa1255.png)
How to deal with it?

**Comment by bastianh** [comment]
you should check the logs in the logs folder. and you should not start the server as root.

**Comment by WolfWings** [comment]
After running into this issue, it turns out the 'install instructions' are somewhat incomplete for bare-naked ubuntu server installs at least:

    apt-get install build-essentials
    npm uninstall -g node-gyp
    npm install -g node-gyp
    npm uninstall -g screeps
    npm install -g screeps

The `build-essentials` package not being installed is the largest obstacle, but trying to install node-gyp without it can cause a broken half-install of node-gyp to exist, so reinstalling node-gyp and then screeps seems to fix it the best.

**Comment by tedivm** [comment]
@WolfWings - there's a PR for [better installation documents](https://github.com/screeps/docs/pull/79) that you might want to read if you're trying to install on ubuntu.

**Comment by WolfWings** [comment]
Maybe, but that's for the documentation site, this is for the NPM itself which doesn't have the documentation site included yet.

If and when they roll the documentation site into the main NPM install then that document would be more valid, but currently there's no indication in the documentation built into the NPM for this missing dependancy. :)

**Comment by artch** [comment]
README has been updated in https://github.com/screeps/screeps/commit/8fefa66b23010b8079859d518da7e9767de0d802.
